from deep_translator import GoogleTranslator

TRANSLATIONS = {
    "en": {
        "welcome": "Welcome to Our Restaurant",
        "main_menu": "Food Menu",
        "cart": "Shopping Cart",
        "reserve": "Table Reservation",
        "curr": "AED",
        "total": "Total",
        "add_item": "Add to Cart",
        "options": "Options",
        "language": "Language",
        "admin_mode": "Admin Mode",
        "password": "Password",
        "logged_in": "Logged in successfully",
        "wrong_pass": "Wrong Password",
        "admin_dash": "Admin Dashboard",
        "orders_tab": "Incoming Orders",
        "res_tab": "Reservations",
        "menu_tab": "Manage Menu",
        "add_new": "Add New Item",
        "item_name_input": "Item Name",
        "price_input": "Price",
        "add_btn": "Add Item",
        "curr_menu": "Current Menu",
        "delete_btn": "Delete",
        "table": "Table",
        "customer": "Customer",
        "no_orders": "No orders yet",
        "no_res": "No reservations yet",
        "empty_cart": "Your cart is currently empty",
        "your_name": "Your Name",
        "table_num": "Table Number (Optional)",
        "confirm_order": "Confirm Order",
        "enter_name_warn": "Please enter your name",
        "order_success": "Order submitted successfully!",
        "res_name": "Reservation Name",
        "guests_count": "Guests Count",
        "date": "Date",
        "time": "Time",
        "reserve_now": "Reserve Now",
    },
    "ar": {
        "welcome": "مرحباً بكم في مطعمنا",
        "main_menu": "قائمة الطعام",
        "cart": "سلة الطلبات",
        "reserve": "حجز طاولة",
        "curr": "درهم",
        "total": "الإجمالي",
        "add_item": "إضافة للسلّة",
        "options": "الخيارات",
        "language": "اللغة",
        "admin_mode": "وضع الأدمن",
        "password": "كلمة السر",
        "logged_in": "تم الدخول بنجاح",
        "wrong_pass": "كلمة السر خاطئة",
        "admin_dash": "لوحة التحكم",
        "orders_tab": "الطلبات الواردة",
        "res_tab": "الحجوزات",
        "menu_tab": "إدارة المنيو",
        "add_new": "إضافة وجبة جديدة",
        "item_name_input": "اسم الوجبة",
        "price_input": "السعر",
        "add_btn": "إضافة الوجبة",
        "curr_menu": "المنيو الحالي",
        "delete_btn": "حذف",
        "table": "الطاولة",
        "customer": "العميل",
        "no_orders": "لا توجد طلبات حتى الآن",
        "no_res": "لا توجد حجوزات حتى الآن",
        "empty_cart": "السلة فارغة حالياً",
        "your_name": "اسمك الكريم",
        "table_num": "رقم الطاولة (اختياري)",
        "confirm_order": "تأكيد الطلب",
        "enter_name_warn": "يرجى كتابة الاسم",
        "order_success": "تم إرسال طلبك بنجاح!",
        "res_name": "اسم الحجز",
        "guests_count": "عدد الأفراد",
        "date": "التاريخ",
        "time": "الوقت",
        "reserve_now": "حجز الآن",
    },
    "ur": {
        "welcome": "ریسٹورانٹ میں خوش آمدید",
        "main_menu": "کھانے کا مینو",
        "cart": "شاپنگ کارٹ",
        "reserve": "ٹیبل کی بکنگ",
        "curr": "درہم",
        "total": "کل",
        "add_item": "کارٹ میں شامل کریں",
        "options": "اختیارات",
        "language": "زبان",
        "admin_mode": "ایڈمن موڈ",
        "password": "پاس ورڈ",
        "logged_in": "کامیابی سے لاگ ان ہو گئے",
        "wrong_pass": "غلط پاس ورڈ",
        "admin_dash": "ایڈمن ڈیش بورڈ",
        "orders_tab": "آرڈرز",
        "res_tab": "بکنگ",
        "menu_tab": "مینو کو کنٹرول کریں",
        "add_new": "نیا آئٹم شامل کریں",
        "item_name_input": "آئٹم کا نام",
        "price_input": "قیمت",
        "add_btn": "شامل کریں",
        "curr_menu": "موجودہ مینو",
        "delete_btn": "حذف کریں",
        "table": "ٹیبل",
        "customer": "کسٹمر",
        "no_orders": "ابھی تک کوئی آرڈر نہیں ہے",
        "no_res": "ابھی تک کوئی بکنگ نہیں ہے",
        "empty_cart": "کارٹ خالی ہے",
        "your_name": "آپ کا نام",
        "table_num": "ٹیبل نمبر",
        "confirm_order": "آرڈر کی تصدیق کریں",
        "enter_name_warn": "براہ کرم اپنا نام درج کریں",
        "order_success": "آرڈر کامیابی کے ساتھ بھیج دیا گیا!",
        "res_name": "بکنگ کا نام",
        "guests_count": "مہمانوں کی تعداد",
        "date": "تاریخ",
        "time": "وقت",
        "reserve_now": "ابھی بک کریں",
    },
    "hi": {
        "welcome": "रेस्तरां में आपका स्वागत है",
        "main_menu": "खाद्य मेनू",
        "cart": "शॉपिंग कार्ट",
        "reserve": "टेबल आरक्षण",
        "curr": "AED",
        "total": "कुल",
        "add_item": "कार्‍ट में जोड़ें",
        "options": "विकल्प",
        "language": "भाषा",
        "admin_mode": "एडमिन मोड",
        "password": "पासवर्ड",
        "logged_in": "सफलतापूर्वक लॉग इन किया गया",
        "wrong_pass": "गलत पासवर्ड",
        "admin_dash": "एडमिन डैशबोर्ड",
        "orders_tab": "आदेश",
        "res_tab": "आरक्षण",
        "menu_tab": "मेनू प्रबंधित करें",
        "add_new": "नई वस्तु जोड़ें",
        "item_name_input": "वस्तु का नाम",
        "price_input": "मूल्य",
        "add_btn": "जोड़ें",
        "curr_menu": "वर्तमान मेनू",
        "delete_btn": "हटाएं",
        "table": "टेबल",
        "customer": "ग्राहक",
        "no_orders": "अभी तक कोई आदेश नहीं है",
        "no_res": "अभी तक कोई आरक्षण नहीं है",
        "empty_cart": "कार्ट खाली है",
        "your_name": "आपका नाम",
        "table_num": "टेबल नंबर",
        "confirm_order": "आदेश की पुष्टि करें",
        "enter_name_warn": "कृपया अपना नाम दर्ज करें",
        "order_success": "आदेश सफलतापूर्वक भेजा गया!",
        "res_name": "आरक्षण का नाम",
        "guests_count": "मेहमानों की संख्या",
        "date": "तिथि",
        "time": "समय",
        "reserve_now": "अभी आरक्षित करें",
    },
    "fil": {
        "welcome": "Maligayang pagdating sa Restaurant",
        "main_menu": "Menu ng Pagkain",
        "cart": "Shopping Cart",
        "reserve": "Reservasyon ng Lamesa",
        "curr": "AED",
        "total": "Kabuuan",
        "add_item": "Ipadala sa Cart",
        "options": "Mga Pagpipilian",
        "language": "Wika",
        "admin_mode": "Admin Mode",
        "password": "Password",
        "logged_in": "Matagumpay na nakapag-login",
        "wrong_pass": "Maling password",
        "admin_dash": "Admin Dashboard",
        "orders_tab": "Mga Order",
        "res_tab": "Mga Reservasyon",
        "menu_tab": "Pamahalaan ang Menu",
        "add_new": "Magdagdag ng Bagong Item",
        "item_name_input": "Pangalan ng Item",
        "price_input": "Presyo",
        "add_btn": "Magdagdag",
        "curr_menu": "Kasalukuyang Menu",
        "delete_btn": "Burahin",
        "table": "Lamesa",
        "customer": "Kustomer",
        "no_orders": "Wala pang mga order",
        "no_res": "Wala pang mga reservasyon",
        "empty_cart": "Walang laman ang cart",
        "your_name": "Ang Iyong Pangalan",
        "table_num": "Numero ng Lamesa",
        "confirm_order": "Kumpirmahin ang Order",
        "enter_name_warn": "Paki-pasok ang iyong pangalan",
        "order_success": "Matagumpay na naipadala ang order!",
        "res_name": "Pangalan ng Reservasyon",
        "guests_count": "Bilang ng Bisita",
        "date": "Petsa",
        "time": "Oras",
        "reserve_now": "Mag-reserba Ngayon",
    },
    "ru": {
        "welcome": "Добро пожаловать в ресторан",
        "main_menu": "Меню блюд",
        "cart": "Корзина покупателя",
        "reserve": "Бронирование столика",
        "curr": "Дирхам",
        "total": "Итого",
        "add_item": "Добавить в корзину",
        "options": "Параметры",
        "language": "Язык",
        "admin_mode": "Режим администратора",
        "password": "Пароль",
        "logged_in": "Успешный вход",
        "wrong_pass": "Неверный пароль",
        "admin_dash": "Панель управления",
        "orders_tab": "Заказы",
        "res_tab": "Бронирования",
        "menu_tab": "Управление меню",
        "add_new": "Добавить новое блюдо",
        "item_name_input": "Название блюда",
        "price_input": "Цена",
        "add_btn": "Добавить",
        "curr_menu": "Текущее меню",
        "delete_btn": "Удалить",
        "table": "Столик",
        "customer": "Клиент",
        "no_orders": "Заказов пока нет",
        "no_res": "Бронирований пока нет",
        "empty_cart": "Корзина пуста",
        "your_name": "Ваше имя",
        "table_num": "Номер столика",
        "confirm_order": "Подтвердить заказ",
        "enter_name_warn": "Пожалуйста, введите ваше имя",
        "order_success": "Заказ успешно отправлен!",
        "res_name": "Имя бронирования",
        "guests_count": "Количество гостей",
        "date": "Дата",
        "time": "Время",
        "reserve_now": "Забронировать",
    },
}

# قاموس الوجبات الثابت (ثنائي الاتجاه)
FOOD_ITEMS_MAP = {
    "شاورما دجاج مع ثومية": {
        "en": "Chicken Shawarma with Garlic",
        "ar": "شاورما دجاج مع ثومية",
        "ur": "تومیا کے ساتھ چکن شاورما",
        "hi": "लहसुन के साथ चिकन शावरमा",
        "fil": "Chicken Shawarma na may Bawang",
        "ru": "Куриная шаурма с чесноком",
    },
    "برجر لحم مشوي": {
        "en": "Grilled Beef Burger",
        "ar": "برجر لحم مشوي",
        "ur": "گرل بیف برگر",
        "hi": "ग्रिल्ड बीफ बर्गर",
        "fil": "Inihaw na Beef Burger",
        "ru": "Говяжий бургер на гриле",
    },
    "عصير برتقال طازج": {
        "en": "Fresh Orange Juice",
        "ar": "عصير برتقال طازج",
        "ur": "تازہ مالٹے کا رس",
        "hi": "ताजा संतरे का रस",
        "fil": "Sariwang Juice ng Dalandan",
        "ru": "Свежевыжатый апельсиновый сок",
    },
    "لحم": {
        "en": "Meat",
        "ar": "لحم",
        "ur": "گوشت",
        "hi": "मांस",
        "fil": "Karne",
        "ru": "Мясо",
    },
    "meat": {
        "en": "Meat",
        "ar": "لحم",
        "ur": "گوشت",
        "hi": "मांस",
        "fil": "Karne",
        "ru": "Мясо",
    },
    "lemon": {
        "en": "Lemon",
        "ar": "ليمون",
        "ur": "لیمن",
        "hi": "नींबू",
        "fil": "Lemon",
        "ru": "Лимон",
    },
    "عصير ليمون": {
        "en": "Lemon Juice",
        "ar": "عصير ليمون",
        "ur": "لیمن جوس",
        "hi": "नींबू पानी",
        "fil": "Juice ng Lemon",
        "ru": "Лимонный сок",
    },
}


def get_ui_text(key, lang_code="en"):
  lang_data = TRANSLATIONS.get(lang_code, TRANSLATIONS["en"])
  return lang_data.get(key, TRANSLATIONS["en"].get(key, key))


def translate_item_from_dict(item_name, lang_code="en"):
  clean_name = str(item_name).strip()
  if not clean_name:
    return ""

  # 1. البحث في خريطة الوجبات الثابتة
  if clean_name in FOOD_ITEMS_MAP:
    return FOOD_ITEMS_MAP[clean_name].get(lang_code, clean_name)

  # البحث العكسي إذا كانت الكلمة مكتوبة بلغة ثانية
  for key, map_dict in FOOD_ITEMS_MAP.items():
    if clean_name.lower() in [v.lower() for v in map_dict.values()]:
      return map_dict.get(lang_code, clean_name)

  # 2. إذا كانت الوجبة جديدة وغير موجودة بالقاموس، ترجمها فوراً عبر GoogleTranslator
  try:
    translated = GoogleTranslator(
        source="auto", target=lang_code
    ).translate(clean_name)
    if translated:
      return translated
  except Exception:
    pass

  return clean_name
